// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaLP2AxjUApP6uSGzC-L_pL95Svhr6V-w',
    appId: '1:195600702842:web:c6aa731ca9f024bea44ac3',
    messagingSenderId: '195600702842',
    projectId: 'currenseepro',
    authDomain: 'currenseepro.firebaseapp.com',
    storageBucket: 'currenseepro.appspot.com',
    measurementId: 'G-YEKB0SEKYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMa07A2DMN76wegpeZRkvsreD6Z1CRt30',
    appId: '1:195600702842:android:3378bc0d4056f7f1a44ac3',
    messagingSenderId: '195600702842',
    projectId: 'currenseepro',
    storageBucket: 'currenseepro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXcDVl0Kk3x3FqEM8zIeMVuGMllY9JQ8w',
    appId: '1:195600702842:ios:0077d584cf8cdd4ea44ac3',
    messagingSenderId: '195600702842',
    projectId: 'currenseepro',
    storageBucket: 'currenseepro.appspot.com',
    iosBundleId: 'com.example.currenseepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXcDVl0Kk3x3FqEM8zIeMVuGMllY9JQ8w',
    appId: '1:195600702842:ios:94279fbe865225c7a44ac3',
    messagingSenderId: '195600702842',
    projectId: 'currenseepro',
    storageBucket: 'currenseepro.appspot.com',
    iosBundleId: 'com.example.currenseepro.RunnerTests',
  );
}
